app/urls.py
# /usr/bin/env python
# -*- coding: utf-8 -*-
# author by xiaotian
from django.conf.urls import url
from app.views import *

urlpatterns = [
    url(r'^home/$', home, name='home'),
    url(r'^register/$', register, name='register'),
    # url(r'^register_view/$', register_view, name='register_view'),
    url(r'^active/', active, name='active'),
    # url(r'^login/$', login, name='login'),
    url(r'^login_handle/$', login_handle, name='login_handle'),
    url(r'^mine/$', mine, name='mine'),
    url(r'^username_check/$', username_check, name='username_check'),
    url(r'^user_active/$', user_active, name='user_active'),
    url(r'^goods_show/$', goods_show, name='goods_show'),
    url(r'^details/$', details, name='details'),
    url(r'^search/$', search, name='search'),
    url(r'^cart/$', cart, name='cart'),
    url(r'^addcart/$', addcart, name='addcart'),
    url(r'^cart_num_add/$', cart_num_add, name='cart_num_add'),
    url(r'^cart_num_reduce/$', cart_num_reduce, name='cart_num_reduce'),
    url(r'^cart_del/$', cart_del, name='cart_del'),
    url(r'^logout/$', logout, name='logout'),
]

meizu_mall/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls', namespace='app')),
]

templates/app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'app:login_handle' %}" method="post">
    <input type="text" name="username"><br>
    <input type="password" name="password"><br>
    <input type="submit">
</form>
</body>
</html>

templates/app/mine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>{{ username }}</p>
    <img src="{{ icon }}" alt="">
</body>
</html>

templates/app/register_send.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>
        <form method="post" enctype="multipart/form-data" action="{% url 'app:register' %}">
            <input type="text" name="username">
            <input type="password" name="password">
            <input type="password" name="repassword">
            <input type="email" name="email">
            <input type="file" name="icon">
            <input type="submit">
        </form>
    </div>
</body>
</html>